### ISSUE TITLE
Scrolling many wordpress categories

### ISSUE THREAD

**Issue by FSNE** [fleshgordo/calibrewordpress#1]
Hey Gordo,

I am trying to use the plugin on a blog with many categories but the window/controls are out of reach when I try to post. Could there be a way to scroll or collapse the categories list?
Thx!

F
![toomanycats](https://f.cloud.github.com/assets/2962492/1145443/dc1f8d60-1e13-11e3-82b8-de4188ec43f0.png)

**Comment by fleshgordo** [comment]
Good one. Never had that problem. So, there are indeed two options: Either we collapse the entire category list into a dropdown menu or add a scrollbar. The first solution seems a bit easier but on the other hand you then can't select multiple categories which might turn out as drawback. Looking into pyQT documentation and will let you know!

**Comment by fleshgordo** [comment]
Hi Femke,

Added a QWidget and ScrollArea. Should work now! Please try!

**Comment by FSNE** [comment]
Yeah!! Very happy with it :-)

F
